import fs from 'fs';
import path from 'path';
import { loadEnv } from 'vite';

export default function generateFirebaseSW() {
  return {
    name: 'generate-firebase-sw',
    configResolved(config) {
      const env = loadEnv(config.mode, process.cwd(), '');
      
      const swContent = `
// ⚠️ AUTO-GENERATED by generate-sw.js plugin. DO NOT EDIT DIRECTLY.
// This file is generated to inject environment variables into the service worker.

importScripts('https://www.gstatic.com/firebasejs/12.13.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/12.13.0/firebase-messaging-compat.js');

firebase.initializeApp({
  apiKey: "${env.VITE_FIREBASE_API_KEY || ''}",
  authDomain: "${env.VITE_FIREBASE_AUTH_DOMAIN || ''}",
  projectId: "${env.VITE_FIREBASE_PROJECT_ID || ''}",
  storageBucket: "${env.VITE_FIREBASE_STORAGE_BUCKET || ''}",
  messagingSenderId: "${env.VITE_FIREBASE_MESSAGING_SENDER_ID || ''}",
  appId: "${env.VITE_FIREBASE_APP_ID || ''}",
  measurementId: "${env.VITE_FIREBASE_MEASUREMENT_ID || ''}",
});

const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
  console.log('[firebase-messaging-sw.js] Received background message ', payload);
  
  const notificationTitle = payload.notification?.title || 'Aura';
  const notificationOptions = {
    body: payload.notification?.body,
    icon: '/favicon.svg',
    badge: '/favicon.svg',
    image: payload.notification?.image || payload.data?.imageUrl,
    data: {
      url: payload.data?.url || '/dashboard'
    }
  };

  self.registration.showNotification(notificationTitle, notificationOptions);
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const url = event.notification.data?.url || '/dashboard';
  
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Check if there is already a window/tab open with the target URL
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        if (client.url.includes(new URL(url, self.location.origin).pathname) && 'focus' in client) {
          return client.focus();
        }
      }
      // If not, open a new window/tab
      if (clients.openWindow) {
        return clients.openWindow(url);
      }
    })
  );
});
`;

      const swPath = path.resolve(config.publicDir, 'firebase-messaging-sw.js');
      if (!fs.existsSync(config.publicDir)) {
        fs.mkdirSync(config.publicDir, { recursive: true });
      }
      fs.writeFileSync(swPath, swContent.trim());
      console.log('✅ Generated firebase-messaging-sw.js in public/');
    }
  };
}
